name: 'Setup Node.js and pnpm'
description: 'Composite action to setup Node.js and pnpm and optionally run pnpm install'
outputs:
  pnpm_store_cache_hit:
    description: 'Whether the pnpm store cache was a hit (true/false)'
    value: ${{ steps.pnpm-store-cache.outputs.cache-hit }}
inputs:
  name: 'Setup Node.js and pnpm'
  description: 'Composite action to setup Node.js and pnpm and optionally run pnpm install'
  outputs:
    pnpm_store_cache_hit:
      description: 'Whether the pnpm store cache was a hit (true/false)'
      value: ${{ steps.pnpm-store-cache.outputs.cache-hit }}
  inputs:
    node-version:
      description: 'Node.js version to install'
      required: false
      default: '18'
    pnpm-version:
      description: 'pnpm version to install (optional)'
      required: false
      default: ''
    cache:
      description: "Enable built-in setup-node cache for package manager (e.g., 'pnpm' or 'npm')"
      required: false
      default: ''
    cache-dependency-path:
      description: 'Path to dependency lockfile for cache key (e.g., pnpm-lock.yaml)'
      required: false
      default: ''
    run-install:
      description: 'Run pnpm install after setup (true/false)'
      required: false
      default: 'false'
  runs:
    using: 'composite'
    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}

      - name: 'Install pnpm'
        uses: pnpm/action-setup@v4
        with:
          pnpm-version: ${{ inputs.pnpm-version }}
          run_install: false

      - name: 'Cache pnpm store'
        id: pnpm-store-cache
        if: ${{ inputs.cache == 'pnpm' && inputs.cache-dependency-path != '' }}
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles(inputs.cache-dependency-path) }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 'Install dependencies (pnpm install)'
        if: ${{ inputs.run-install == 'true' }}
        run: pnpm install --frozen-lockfile
  node-version:
